global:
  name: LF Interactive Landscape
  short_name: LF
  repo: jmertic/lf-landscape
  website: 'https://landscape.linuxfoundation.org'
  short_domain: l.linuxfoundation.org
  company_url: 'https://linuxfoundation.org'
  email: info@linuxfoundation.org
  self: 'https://www.crunchbase.com/organization/linux-foundation'
  slack_channel: T08PSQ7BQ/BM3K5125V/VfQL9ybcXrwpnLAdKdU8WQrr
  meta:
    title: LF Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@linuxfoundation'
    google_site_verification: crYr16dyu7npMmK-fw42gMkXKTWg_A-7c2PosXgtPZo
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: LF Member Company
  flags:
    companies: LF Member Company
    hide_license_for_categories:
      - LF Members
twitter:
  search: landscape.linuxfoundation.org
  url: 'https://landscape.linuxfoundation.org'
  text: LF Landscape from @linuxfoundation
relation:
  label: LF Relation
  url: lf
  values:
    - id: hosted
      label: LF Projects
      children:
        - id: graduated
          label: Graduated LF Projects
          prefix: LF
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating LF Projects
          prefix: LF
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: LF Incubating
          big_picture_color: 'rgb(83, 113, 189)'
    - id: company
      label: LF Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LF Member Products/Projects
      tag: LF Member
    - id: false
      label: Non-LF Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: LF
    label: Platinum Member
    funding: Platinum
    is_large: true
  Gold:
    name: LF
    label: Gold Member
    funding: Gold
    is_large: true
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Interactive Landscape</h1> The Linux foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccnceu20'
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: OS cards by age
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=license&license=open-source
    label: Group by license
  - url: /format=card-mode&grouping=no&license=open-source&sort=latest-commit
    label: OS cards by latest commit
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Linux Foundation Landscape
    fullscreen_header: See the interactive landscape at l.linuxfoundation.org
    size:
      width: 1165
      height: 900
    fullscreen_size:
      width: 1165
      height: 900
    elements:
      - type: VerticalCategory
        category: Vertical Specific
        cols: 6
        width: 240
        height: 300
        top: 10
        left: 900
        color: 'rgb(78,171,207)'
        fit_height: false
      - type: HorizontalCategory
        category: Cloud Computing
        rows: 4
        width: 880
        height: 170
        top: 10
        left: 0
        color: 'rgb(104,145,145)'
        fit_width: true
      - type: HorizontalCategory
        category: Development and Tooling
        rows: 4
        width: 600
        height: 190
        top: 200
        left: 0
        color: 'rgb(108,135,75)'
        fit_width: true
      - type: HorizontalCategory
        category: 'Data, Anayltics, and AI'
        rows: 3
        width: 880
        height: 140
        top: 420
        left: 0
        color: 'rgb(130,207,231)'
        fit_width: true
      - type: VerticalCategory
        category: Other
        cols: 6
        width: 240
        height: 140
        top: 430
        left: 900
        color: 'rgb(130,207,231)'
        fit_width: true
      - type: HorizontalCategory
        category: Infrastructure
        rows: 4
        width: 1140
        height: 180
        top: 600
        left: 0
        color: 'rgb(130,207,231)'
        fit_width: false
      - type: VerticalCategory
        category: Standards
        cols: 6
        width: 240
        height: 100
        top: 320
        left: 900
        color: 'rgb(130,207,231)'
        fit_width: true
      - type: HorizontalCategory
        category: Community and Compliance
        rows: 4
        width: 270
        height: 190
        top: 200
        left: 610
        color: 'rgb(130,207,231)'
        fit_width: false
  third:
    tab_index: 1
    url: members
    name: Members
    title: LF Members
    fullscreen_header: Become a LF member at cncf.io/join or view the interactive member landscape at m.cncf.io
    fullscreen_hide_grey_logos: true
    size:
      width: 1165
      height: 900
    fullscreen_size:
      width: 1165
      height: 900
    elements:
      - type: VerticalCategory
        category: Platinum
        cols: 18
        width: 750
        height: 160
        top: 0
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_height: true
      - type: VerticalCategory
        category: Gold
        cols: 30
        width: 1150
        height: 100
        top: 180
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_height: true
      - type: LandscapeInfo
        width: 365
        height: 160
        top: 0
        left: 790
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore open source projects hosted by the Linux Foundation , and also shows the member companies of the Linux Foundation.
            top: 15
            left: 130
            right: 130
            font_size: 10
          - type: image
            image: qr.svg
            top: 20
            left: 20
            width: 90
            height: 90
          - type: title
            title: l.linuxfoundation.org
            top: 110
            left: 5
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 20
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 80
    category: LF Member Company
test:
  header: LF Interactive Landscape
  section: LF Member Company
  logo: ibm.svg
